# Generated by Django 5.0.1 on 2024-02-13 16:20
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statuses', '0003_alter_status_options_remove_status_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=25500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creation date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performer', to=settings.AUTH_USER_MODEL, verbose_name='Performer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='statuses.status', verbose_name='Status')),
            ],
        ),
    ]
