# Generated by Django 5.0.1 on 2024-03-15 15:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=25500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAndLabelNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
