# Generated by Django 5.0.1 on 2024-03-05 17:46
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_options_remove_status_updated_at_and_more'),
        ('tasks', '0002_taskandlabelnode_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.status', verbose_name='Status'),
        ),
    ]
